# fly.toml app configuration file generated for syncwatch on 2024-11-27T16:20:57+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'litsi'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 4
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
